@startuml

actor User

component Private
component Profile
component DFS
component "Serialize/Deserialize" as serde
component Credentials
component Document
component Keystore
component CMSEncryption

User -down-> Private : read private file

Private =right=> Profile
Private <-- Profile
Profile =right=> DFS
Profile <-- DFS
Profile =down=> serde
Profile <-- serde

Private =right=> Credentials
Private <-- Credentials

Private =right=> Keystore
Private <-- Keystore

Private =right=> Document
Private <-- Document

Document =right=> CMSEncryption
Document <-- CMSEncryption

@enduml