@startuml

cloud "DocusafeServices" {

left to right direction
  together {
    cloud "Inbox" {
    }

    cloud "Private" {
    }

    cloud "Profile" {
    }
  }


  package "CredentialsModule" {
    [BucketAccessService]
    [PublicKeyService]
    [PrivateKeyService]
    [DFSCredentialsService]
  }

  package "KeyStoreModule" {
    [KeyStoreService]
  }

  package "DocumentModule" {
    [DocumentReadService]
    [DocumentWriteService]
    [DocumentListService]
    [ListPathDecryptingServiceImpl]
    [ListPathNonDecryptingServiceImpl]
  }

  package "DFSModule" {
    [DFSConnectionService]
  }

  package "CMSEncryptionModule" {
    [CMSEncryptionService]
  }

  package "Serde (serialization)" as serde {
      [GsonSerde]
    }

  package "InboxActionsModule" as inbox {
    [ListInbox]
    [ReadFromInbox]
    [WriteToInbox]
  }

  package "PrivateActionsModule" as private {
    [ListPrivate]
    [ReadFromPrivate]
    [WriteToPrivate]
  }

  package "ProfileModule" as profile {
    [ProfileRetrievalService]
    [ProfileRegistrationService]
    [ProfileRemovalService]
  }

  Inbox -> inbox
  Private -> private
  Profile -> profile

  inbox -down-> CredentialsModule
  inbox -down-> DocumentModule
  inbox -down-> KeyStoreModule

  private -down-> CredentialsModule
  private -down-> DocumentModule
  private -down-> KeyStoreModule

  profile -down-> serde
  profile -down-> KeyStoreModule
  profile -down-> DFSModule
}
@enduml
