@startuml

actor User as u
u->"UserIdUtilDelegate" as r : getHomeBucketDirectory
r->"Caching layer" as c : get private directory layout
c->"Directory server" as d : GET /api/lookup/private
d->"Lookup service" as ls : read metadata
ls->d : metadata
d->c : private directory layout
c->r : private directory layout
r->u : User keystore directory

@enduml