@startuml
skinparam SequenceMessageAlign center

actor User

activate User
User -> DFSDatasafeService : createUser
activate DFSDatasafeService
DFSDatasafeService -> KeyStoreService : createKeyStore
activate KeyStoreService
KeyStoreService --> DFSDatasafeService : users public keystore
deactivate KeyStoreService
DFSDatasafeService -> DFSDatasafeService : create DFSCredential
DFSDatasafeService -> DFSCredentialsService : registerDFS
activate DFSCredentialsService
DFSCredentialsService -> CMSEncryptionService : encrypt(DFSCredentials)
activate CMSEncryptionService
CMSEncryptionService --> DFSCredentialsService : encrypted data
deactivate CMSEncryptionService
DFSCredentialsService -> "SYSTEM DFS\nDFSConnectionService" as sysDFS : storeBlob
DFSCredentialsService -> DFSDatasafeService : return
deactivate DFSCredentialsService
DFSDatasafeService -> "USER DFS\nDFSConnectionService" as usrDFS : NEW
DFSDatasafeService -> KeyStoreService : createKeyStore
activate KeyStoreService
KeyStoreService --> DFSDatasafeService : users secret keystore
deactivate KeyStoreService
DFSDatasafeService -> usrDFS : storeBlob(users secret keystore)
DFSDatasafeService ->  KeyStoreService : getAllPublicKeys(users secret keystore)
activate KeyStoreService
KeyStoreService --> DFSDatasafeService : List<PublicKey>
deactivate KeyStoreService
DFSDatasafeService -> sysDFS : storeBlob(List<PublicKey>)
DFSDatasafeService --> User : return
deactivate DFSDatasafeService
deactivate User
@enduml