@startuml
title Store/Read/Delete Private Document
hide footbox
actor User

participant "REST" as r
participant "Lookup Service" as ls
participant "VFS Service" as vs
participant "Storage Service" as ss
participant "S3" as s3


User->ls : get my keypair from keystore (login/password)
ls->User : user's keypair

User->ls : get my DFS Credentials for **/folder**
ls->User : DFS Creds(accessKey, secretKey etc)


User->ss : encrypt and save/decrypt and read/verify and delete file using keypair, dfs access
ss->s3 : persistence
s3->ss : success
ss->User : success
@enduml