@startuml
title Send file to inbox
hide footbox
actor User

participant "REST" as r
participant "Lookup Service" as ls
participant "VFS Service" as vs
participant "Storage Service" as ss
participant "S3" as s3


User->ls : get User2 inbox info <&key>(login/password)
ls->User : User2 **<&key>public key** and **/inbox** access creds


User->ss : encrypt and save file to user's inbox location
ss->s3 : persistence
s3->ss : success
ss->User : success
@enduml