@startuml
actor User
User->"Lookup server (default) / Interface" as ls : Get my inbox file list with **<&key>login/password**
box "Internal flow within lookup server"
ls->"Public key Service" as lss : get User public metadata from Lookup DFS
lss->"Lookup DFS Service" as DFS : Read public key store
DFS->lss : User **<&key>public key**
lss->DFS : Read public store for User using **<&key>public key**
DFS->lss : User inbox location and access key **s3:bucket : <&key>access**
end box
lss->ls : User inbox path **s3:bucket** and **<&key>access** credentials
ls->"Storage Service" as ss : access inbox **s3:bucket** storage using **<&key>access** credentials with **<&key>password**
ss->"Storage adapter" as sa : read keystore
sa->ss : user keystore
ss->ss : Decrypt **keystore** using **<&key>password**
ss->sa : List all inbox files
ss->ls : Inbox file list
ls->User : List of files in inbox
@enduml