@startuml
actor User
User->"Lookup server (default) / Interface" as ls : Share my **<&file>file** with User 2
box "Internal flow within lookup server"
ls->"Public key Service" as lss : get User 2 public metadata from Lookup DFS
lss->"Lookup DFS Service" as DFS : Read public key store
DFS->lss : User 2 **<&key>public key**
lss->DFS : Read public store for User 2 using **<&key>public key**
DFS->lss : User 2 inbox location and access key **s3:bucket1 : <&key>access1**
end box
lss->ls : Inbox location and access key **s3:bucket1 : <&key>access1**, **<&key>public key**
ls->"Storage Service" as ss : put **<&file>file** to **s3:bucket1** with **<&key>access** encrypting with **<&key>public key**
ss->ss : Encrypt **<&file>file** using User 2 **<&key>public key**
ss->"Storage adapter" as sa : Save encrypted **<&file>file** to User 2 **s3:bucket1** using **<&key>access**
sa->ss : Signal done
ss->ls
ls->User : Done
@enduml