@startuml
skinparam SequenceMessageAlign center

actor User

User -> DFSDatasafeService : storeDocument
activate User
activate DFSDatasafeService
DFSDatasafeService -> DFSCredentialService : getCredentials
activate DFSCredentialService
DFSCredentialService -> "SYSTEM DFS\nDFSConnectionService" as sysDFS : readBlob(users public keystore)
activate sysDFS
sysDFS --> DFSCredentialService : return
deactivate sysDFS
DFSCredentialService -> sysDFS : readBlob(DFSConnectionDetails)
activate sysDFS
sysDFS --> DFSCredentialService : return
deactivate sysDFS
DFSCredentialService -> CMSEncryptionService : decrypt(DFSCredentials)
activate CMSEncryptionService
CMSEncryptionService --> DFSCredentialService : decrypted DFSCredentials
deactivate CMSEncryptionService
DFSCredentialService --> DFSDatasafeService : return DFSCredentials
deactivate DFSCredentialService
DFSDatasafeService -> "USER DFS\nDFSConnectionService" as usrDFS : NEW
DFSDatasafeService -> sysDFS : readBlob(users public keys)
activate sysDFS
sysDFS --> DFSDatasafeService : return
deactivate sysDFS
DFSDatasafeService -> CMSEncryptionService : encrypt(document, publicKey)
activate CMSEncryptionService
CMSEncryptionService --> DFSDatasafeService : encrypted document (CMSEnvelope)
deactivate CMSEncryptionService
DFSDatasafeService -> usrDFS : readBlob(user private keystore)
activate usrDFS
usrDFS --> DFSDatasafeService : return (user private keystore)
deactivate usrDFS
DFSDatasafeService -> KeystoreService : getSecretKey
activate KeystoreService
KeystoreService --> DFSDatasafeService : return secret key
deactivate KeystoreService
DFSDatasafeService -> BucketPathEncryptionService : encrypt bucketpath with secret key
activate BucketPathEncryptionService
BucketPathEncryptionService --> DFSDatasafeService : return
deactivate BucketPathEncryptionService
DFSDatasafeService -> usrDFS : storeBlob(encrypted path, encrypted document)
activate usrDFS
usrDFS --> DFSDatasafeService : return
deactivate usrDFS
DFSDatasafeService --> User : return
deactivate DFSDatasafeService
deactivate User
@enduml