@startuml

actor User

node ts [
  **Transactional layer**
  ===
  REST api
]

node ds [
  **Docusafe server**
  ===
  REST api
]

cloud "Lookup server" as LS {
  node ls [
    **Lookup service**
    ===
    private storage(s) location and ACESS_KEY/SECRET_KEY
    inbox storage location and ACESS_KEY/SECRET_KEY
  ]
  node vfs [
    **Virtual filesystem service**
    ===
    create virtual filesystem (new Docusafe-managed user)
    mount virtual filesystem (register user filesystem)
  ]
}

node sas [
  **Storage adapter service**
  ===
  Encrypt/decrypt data stream
  List files within storage
  Read/write bytes to storage using ACESS_KEY/SECRET_KEY
]

User <-down-> ts
User <-down-> ds

ts -down-> ds
ds -down-> ts
ds <|--|> LS
ds <|--|> sas
LS <|--|> sas
ls <|--|> sas
vfs <|--|> sas
@enduml