@startuml

skinparam SequenceMessageAlign center

activate PRIVATE
' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
PRIVATE -> PRIVATE : resolvePrivateLocation

activate PRIVATE
' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
PRIVATE -> Profile : privateProfile

activate Profile
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
Profile -> Profile : privateProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : locatePrivateProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : BucketPath
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : getBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS : Payload
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> SERDE : fromJson

activate SERDE
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
Profile <-- SERDE : T
deactivate SERDE

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : UserPrivateProfile
deactivate Profile

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
PRIVATE <-- Profile : UserPrivateProfile
deactivate Profile

deactivate PRIVATE

' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
PRIVATE -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
Credentials -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Credentials <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
PRIVATE <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
PRIVATE -> Document : list

activate Document
activate Document
' de.adorsys.datasafe.business.impl.document.list.ListPathDecryptingServiceImpl
Document -> Document : list

activate Document
' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
Document -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Document <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
Document -> DFS : list

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Document <-- DFS : List
deactivate DFS


' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
Document <-- Document : Stream
deactivate Document

Document <-- Document : Stream

deactivate Document
' de.adorsys.datasafe.business.api.deployment.document.DocumentListService
PRIVATE <-- Document : Stream
deactivate Document

deactivate PRIVATE
@enduml
