@startuml

skinparam SequenceMessageAlign center

activate INBOX
' de.adorsys.datasafe.business.api.inbox.actions.ReadFromInboxImpl
INBOX -> INBOX : resolveFileLocation

activate INBOX
' de.adorsys.datasafe.business.api.inbox.actions.ReadFromInboxImpl
INBOX -> Profile : publicProfile

activate Profile
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
Profile -> Profile : publicProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : locatePublicProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : BucketPath
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : getBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS : Payload
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> SERDE : fromJson

activate SERDE
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
Profile <-- SERDE : T
deactivate SERDE

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : UserPublicProfile
deactivate Profile

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
INBOX <-- Profile : UserPublicProfile
deactivate Profile

deactivate INBOX

' de.adorsys.datasafe.business.api.inbox.actions.ReadFromInboxImpl
INBOX -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
Credentials -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Credentials <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
INBOX <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.business.api.inbox.actions.ReadFromInboxImpl
INBOX -> KeyStore : keystore

activate KeyStore
' de.adorsys.datasafe.business.api.deployment.keystore.PrivateKeyService
KeyStore -> Credentials : keystore

activate Credentials
' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
Credentials -> Credentials : privateAccessFor

activate Credentials
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials -> Credentials : privateUserCredentials

activate Credentials
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Credentials <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
Credentials <-- Credentials : DFSCredentials
deactivate Credentials

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
Credentials <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
Credentials <-- Credentials : DFSAccess
deactivate Credentials

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> Profile : privateProfile

activate Profile
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
Profile -> Profile : privateProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : locatePrivateProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : BucketPath
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : getBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS : Payload
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> SERDE : fromJson

activate SERDE
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
Profile <-- SERDE : T
deactivate SERDE

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : UserPrivateProfile
deactivate Profile

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
Credentials <-- Profile : UserPrivateProfile
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Credentials <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> Profile : privateKeyStoreAuth

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Credentials <-- Profile : KeyStoreAuth
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> DFS : getBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Credentials <-- DFS : Payload
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
Credentials -> Profile : privateKeyStoreAuth

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Credentials <-- Profile : KeyStoreAuth
deactivate Profile

deactivate Credentials

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
KeyStore <-- Credentials : KeyStoreAccess
deactivate Credentials

' de.adorsys.datasafe.business.api.deployment.keystore.PrivateKeyService
INBOX <-- KeyStore : KeyStoreAccess
deactivate KeyStore

' de.adorsys.datasafe.business.api.inbox.actions.ReadFromInboxImpl
INBOX -> Document : read

activate Document
' de.adorsys.datasafe.business.api.deployment.document.DocumentReadService
Document -> Document : read

activate Document
' de.adorsys.datasafe.encrypiton.impl.document.cmsocument.CMSDocumentReadService
Document -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Document <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
Document -> DFS : getBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Document <-- DFS : Payload
deactivate DFS

' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
Document -> CMS : decrypt

activate CMS
' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
CMS -> CMS : decrypt

activate CMS
' de.adorsys.datasafe.encrypiton.impl.cmsencryption.CMSEncryptionServiceImpl
CMS <-- CMS : DocumentContent
deactivate CMS

' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
Document <-- CMS : DocumentContent
deactivate CMS

' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
Document <-- Document :
deactivate Document

' de.adorsys.datasafe.business.api.deployment.document.DocumentReadService
INBOX <-- Document :
deactivate Document

deactivate INBOX
@enduml
