@startuml

skinparam SequenceMessageAlign center

activate DocusafeServiceAdapterTest
' de.adorsys.datasafe.business.impl.impl.DocusafeServiceAdapterTest
DocusafeServiceAdapterTest -> DocusafeServiceAdapterImpl : createUser

activate DocusafeServiceAdapterImpl
' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DefaultDocusafeServices : userProfile

activate DefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DefaultDocusafeServices -> DaggerDefaultDocusafeServices : userProfile

activate DaggerDefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DaggerDefaultDocusafeServices
DefaultDocusafeServices <-- DaggerDefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DaggerDefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DocusafeServiceAdapterImpl <-- DefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> Profile : registerPublic

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : locatePublicProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : BucketPath
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : createContainer

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> SERDE : toJson

activate SERDE
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
Profile <-- SERDE : String
deactivate SERDE

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : putBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DocusafeServiceAdapterImpl <-- Profile :
deactivate Profile

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DefaultDocusafeServices : userProfile

activate DefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DefaultDocusafeServices -> DaggerDefaultDocusafeServices : userProfile

activate DaggerDefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DaggerDefaultDocusafeServices
DefaultDocusafeServices <-- DaggerDefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DaggerDefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DocusafeServiceAdapterImpl <-- DefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> Profile : registerPrivate

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : systemDfs

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : DFSAccess
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : locatePrivateProfile

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile : BucketPath
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : createContainer

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> SERDE : toJson

activate SERDE
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
Profile <-- SERDE : String
deactivate SERDE

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : putBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : createKeyStore

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> Profile : privateKeyStoreAuth

activate Profile
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
Profile <-- Profile : KeyStoreAuth
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> KeyStore : createKeyStore

activate KeyStore
' de.adorsys.datasafe.business.api.deployment.keystore.KeyStoreService
Profile <-- KeyStore : KeyStore
deactivate KeyStore

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFS -> DFS : obtain

activate DFS
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFS <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
Profile <-- DFS : DFSConnection
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : createContainer

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile -> DFS : putBlob

activate DFS
' de.adorsys.dfs.connection.api.service.api.DFSConnection
Profile <-- DFS :
deactivate DFS

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
Profile <-- Profile :
deactivate Profile

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DocusafeServiceAdapterImpl <-- Profile :
deactivate Profile

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterTest <-- DocusafeServiceAdapterImpl :
deactivate DocusafeServiceAdapterImpl

@enduml