@startuml

skinparam SequenceMessageAlign center

activate DocusafeServiceAdapterTest
' de.adorsys.datasafe.business.impl.impl.DocusafeServiceAdapterTest
DocusafeServiceAdapterTest -> DocusafeServiceAdapterImpl : createUser

activate DocusafeServiceAdapterImpl
' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DefaultDocusafeServices : userProfile

activate DefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DefaultDocusafeServices -> DaggerDefaultDocusafeServices : userProfile

activate DaggerDefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DaggerDefaultDocusafeServices
DefaultDocusafeServices <-- DaggerDefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DaggerDefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DocusafeServiceAdapterImpl <-- DefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DFSBasedProfileStorageImpl : registerPublic

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePublicProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : createContainer

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : toJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : String
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DocusafeServiceAdapterImpl <-- DFSBasedProfileStorageImpl :  
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DefaultDocusafeServices : userProfile

activate DefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DefaultDocusafeServices -> DaggerDefaultDocusafeServices : userProfile

activate DaggerDefaultDocusafeServices
' de.adorsys.datasafe.business.impl.service.DaggerDefaultDocusafeServices
DefaultDocusafeServices <-- DaggerDefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DaggerDefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DefaultDatasafeServices
DocusafeServiceAdapterImpl <-- DefaultDocusafeServices : DFSBasedProfileStorageImpl
deactivate DefaultDocusafeServices

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterImpl -> DFSBasedProfileStorageImpl : registerPrivate

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePrivateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : createContainer

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : toJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : String
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : createKeyStore

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : privateKeyStoreAuth

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : KeyStoreAuth
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> KeyStoreService : createKeyStore

activate KeyStoreService
' de.adorsys.datasafe.business.api.deployment.keystore.KeyStoreService
DFSBasedProfileStorageImpl <-- KeyStoreService : KeyStore
deactivate KeyStoreService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : createContainer

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl :  
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DocusafeServiceAdapterImpl <-- DFSBasedProfileStorageImpl :  
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.service.DocusafeServiceAdapterImpl
DocusafeServiceAdapterTest <-- DocusafeServiceAdapterImpl :  
deactivate DocusafeServiceAdapterImpl

@enduml
