@startuml

skinparam SequenceMessageAlign center

activate ListPrivateImpl
' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
ListPrivateImpl -> ListPrivateImpl : resolvePrivateLocation

activate ListPrivateImpl
' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
ListPrivateImpl -> ProfileRetrievalService : privateProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : privateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePrivateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPrivateProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
ListPrivateImpl <-- ProfileRetrievalService : UserPrivateProfile
deactivate ProfileRetrievalService

deactivate ListPrivateImpl

' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
ListPrivateImpl -> BucketAccessService : privateAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : privateAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : privateUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : privateUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
ListPrivateImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.privatestore.impl.actions.ListPrivateImpl
ListPrivateImpl -> DocumentListService : list

activate DocumentListService
activate ListPathDecryptingServiceImpl
' de.adorsys.datasafe.business.impl.document.list.ListPathDecryptingServiceImpl
ListPathDecryptingServiceImpl -> ListPathNonDecryptingServiceImpl : list

activate ListPathNonDecryptingServiceImpl
' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
ListPathNonDecryptingServiceImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
ListPathNonDecryptingServiceImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
ListPathNonDecryptingServiceImpl -> DFSConnection : list

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
ListPathNonDecryptingServiceImpl <-- DFSConnection : List
deactivate DFSConnection


' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
ListPathDecryptingServiceImpl <-- ListPathNonDecryptingServiceImpl : Stream
deactivate ListPathNonDecryptingServiceImpl

DocumentListService <-- ListPathDecryptingServiceImpl : Stream

deactivate ListPathDecryptingServiceImpl
' de.adorsys.datasafe.business.api.deployment.document.DocumentListService
ListPrivateImpl <-- DocumentListService : Stream
deactivate DocumentListService

deactivate ListPrivateImpl
@enduml
