@startuml

skinparam SequenceMessageAlign center

activate ListInboxImpl
' de.adorsys.datasafe.business.impl.inbox.actions.ListInboxImpl
ListInboxImpl -> ListInboxImpl : resolveInboxLocation

activate ListInboxImpl
' de.adorsys.datasafe.business.impl.inbox.actions.ListInboxImpl
ListInboxImpl -> ProfileRetrievalService : publicProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : publicProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePublicProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPublicProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
ListInboxImpl <-- ProfileRetrievalService : UserPublicProfile
deactivate ProfileRetrievalService

deactivate ListInboxImpl

' de.adorsys.datasafe.business.impl.inbox.actions.ListInboxImpl
ListInboxImpl -> BucketAccessService : privateAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : privateAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : privateUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : privateUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
ListInboxImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.business.impl.inbox.actions.ListInboxImpl
ListInboxImpl -> DocumentListService : list

activate DocumentListService
' de.adorsys.datasafe.business.api.storage.StorageListService

' de.adorsys.datasafe.business.impl.inbox.actions.ListInboxImpl
DocumentListService -> ListPathNonDecryptingServiceImpl : list

activate ListPathNonDecryptingServiceImpl
' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
ListPathNonDecryptingServiceImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
ListPathNonDecryptingServiceImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.document.list.ListPathNonDecryptingServiceImpl
ListPathNonDecryptingServiceImpl -> DFSConnection : list

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
ListPathNonDecryptingServiceImpl <-- DFSConnection : List
deactivate DFSConnection

DocumentListService <-- ListPathNonDecryptingServiceImpl : Stream

deactivate ListPathNonDecryptingServiceImpl

ListInboxImpl <-- DocumentListService : Stream

deactivate DocumentListService

deactivate ListInboxImpl

@enduml
