@startuml

skinparam SequenceMessageAlign center

activate ReadFromPrivateImpl
' de.adorsys.datasafe.privatestore.impl.actions.ReadFromPrivateImpl
ReadFromPrivateImpl -> ReadFromPrivateImpl : resolveFileLocation

activate ReadFromPrivateImpl
' de.adorsys.datasafe.privatestore.impl.actions.ReadFromPrivateImpl
ReadFromPrivateImpl -> ProfileRetrievalService : privateProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : privateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePrivateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPrivateProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
ReadFromPrivateImpl <-- ProfileRetrievalService : UserPrivateProfile
deactivate ProfileRetrievalService

deactivate ReadFromPrivateImpl

' de.adorsys.datasafe.privatestore.impl.actions.ReadFromPrivateImpl
ReadFromPrivateImpl -> BucketAccessService : privateAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : privateAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : privateUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : privateUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
ReadFromPrivateImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.privatestore.impl.actions.ReadFromPrivateImpl
ReadFromPrivateImpl -> PrivateKeyService : keystore

activate PrivateKeyService
' de.adorsys.datasafe.business.api.deployment.keystore.PrivateKeyService
PrivateKeyService -> DFSPrivateKeyServiceImpl : keystore

activate DFSPrivateKeyServiceImpl
' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> BucketAccessService : privateAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : privateAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : privateUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : privateUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.DFSCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.profile.dfs.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.deployment.credentials.BucketAccessService
DFSPrivateKeyServiceImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> ProfileRetrievalService : privateProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : privateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePrivateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.profile.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.operations.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPrivateProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.deployment.profile.ProfileRetrievalService
DFSPrivateKeyServiceImpl <-- ProfileRetrievalService : UserPrivateProfile
deactivate ProfileRetrievalService

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSPrivateKeyServiceImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> DFSSystem : privateKeyStoreAuth

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSPrivateKeyServiceImpl <-- DFSSystem : KeyStoreAuth
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSPrivateKeyServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
DFSPrivateKeyServiceImpl -> DFSSystem : privateKeyStoreAuth

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.operations.DFSSystem
DFSPrivateKeyServiceImpl <-- DFSSystem : KeyStoreAuth
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.keys.DFSPrivateKeyServiceImpl
PrivateKeyService <-- DFSPrivateKeyServiceImpl : KeyStoreAccess
deactivate DFSPrivateKeyServiceImpl

' de.adorsys.datasafe.business.api.deployment.keystore.PrivateKeyService
ReadFromPrivateImpl <-- PrivateKeyService : KeyStoreAccess
deactivate PrivateKeyService

' de.adorsys.datasafe.privatestore.impl.actions.ReadFromPrivateImpl
ReadFromPrivateImpl -> DocumentReadService : read

activate DocumentReadService
' de.adorsys.datasafe.business.api.deployment.document.DocumentReadService
DocumentReadService -> CMSDocumentReadService : read

activate CMSDocumentReadService
' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
CMSDocumentReadService -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
DFSConnectionService -> DFSConnectionServiceImpl : obtain

activate DFSConnectionServiceImpl
' de.adorsys.datasafe.business.impl.dfs.DFSConnectionServiceImpl
DFSConnectionService <-- DFSConnectionServiceImpl : DFSConnection
deactivate DFSConnectionServiceImpl

' de.adorsys.datasafe.business.api.deployment.dfs.DFSConnectionService
CMSDocumentReadService <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.encrypiton.impl.document.cmsocument.CMSDocumentReadService
CMSDocumentReadService -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
CMSDocumentReadService <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
CMSDocumentReadService -> CMSEncryptionService : decrypt

activate CMSEncryptionService
' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
CMSEncryptionService -> CMSEncryptionServiceImpl : decrypt

activate CMSEncryptionServiceImpl
' de.adorsys.datasafe.encrypiton.impl.cmsencryption.CMSEncryptionServiceImpl
CMSEncryptionService <-- CMSEncryptionServiceImpl : DocumentContent
deactivate CMSEncryptionServiceImpl

' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
CMSDocumentReadService <-- CMSEncryptionService : DocumentContent
deactivate CMSEncryptionService

' de.adorsys.datasafe.encrypiton.impl.document.CMSDocumentReadServiceReadService
DocumentReadService <-- CMSDocumentReadService :  
deactivate CMSDocumentReadService

' de.adorsys.datasafe.business.api.deployment.document.DocumentReadService
ReadFromPrivateImpl <-- DocumentReadService :  
deactivate DocumentReadService

deactivate ReadFromPrivateImpl

@enduml
