@startuml

skinparam SequenceMessageAlign center

activate WriteToPrivateImpl
' de.adorsys.datasafe.business.impl.privatestore.actions.WriteToPrivateImpl
WriteToPrivateImpl -> WriteToPrivateImpl : resolveFileLocation

activate WriteToPrivateImpl
' de.adorsys.datasafe.business.impl.privatestore.actions.WriteToPrivateImpl
WriteToPrivateImpl -> ProfileRetrievalService : privateProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : privateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePrivateProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPrivateProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
WriteToPrivateImpl <-- ProfileRetrievalService : UserPrivateProfile
deactivate ProfileRetrievalService

deactivate WriteToPrivateImpl

' de.adorsys.datasafe.business.impl.privatestore.actions.WriteToPrivateImpl
WriteToPrivateImpl -> BucketAccessService : privateAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : privateAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : privateUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : privateUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
WriteToPrivateImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.business.impl.privatestore.actions.WriteToPrivateImpl
WriteToPrivateImpl -> PublicKeyService : publicKey

activate PublicKeyService
' de.adorsys.datasafe.business.api.directory.profile.keys.PublicKeyService
PublicKeyService -> DFSPublicKeyServiceImpl : publicKey

activate DFSPublicKeyServiceImpl
' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> BucketAccessService : publicAccessFor

activate BucketAccessService
' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
BucketAccessService -> BucketAccessServiceImpl : publicAccessFor

activate BucketAccessServiceImpl
' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessServiceImpl -> DFSCredentialsService : publicUserCredentials

activate DFSCredentialsService
' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
DFSCredentialsService -> DFSCredentialsServiceImpl : publicUserCredentials

activate DFSCredentialsServiceImpl
' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsServiceImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSCredentialsServiceImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.SystemCredentialsServiceImpl
DFSCredentialsService <-- DFSCredentialsServiceImpl : DFSCredentials
deactivate DFSCredentialsServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.credentials.DFSCredentialsService
BucketAccessServiceImpl <-- DFSCredentialsService : DFSCredentials
deactivate DFSCredentialsService

' de.adorsys.datasafe.business.impl.credentials.BucketAccessServiceImpl
BucketAccessService <-- BucketAccessServiceImpl : DFSAccess
deactivate BucketAccessServiceImpl

' de.adorsys.datasafe.business.api.storage.dfs.BucketAccessService
DFSPublicKeyServiceImpl <-- BucketAccessService : DFSAccess
deactivate BucketAccessService

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> ProfileRetrievalService : publicProfile

activate ProfileRetrievalService
' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
ProfileRetrievalService -> DFSBasedProfileStorageImpl : publicProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSSystem : systemDfs

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSBasedProfileStorageImpl <-- DFSSystem : DFSAccess
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSBasedProfileStorageImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSBasedProfileStorageImpl : locatePublicProfile

activate DFSBasedProfileStorageImpl
' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl <-- DFSBasedProfileStorageImpl : BucketPath
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSBasedProfileStorageImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
DFSBasedProfileStorageImpl -> GsonSerde : fromJson

activate GsonSerde
' de.adorsys.datasafe.business.impl.serde.GsonSerde
DFSBasedProfileStorageImpl <-- GsonSerde : T
deactivate GsonSerde

' de.adorsys.datasafe.business.impl.profile.DFSBasedProfileStorageImpl
ProfileRetrievalService <-- DFSBasedProfileStorageImpl : UserPublicProfile
deactivate DFSBasedProfileStorageImpl

' de.adorsys.datasafe.business.api.directory.profile.operations.ProfileRetrievalService
DFSPublicKeyServiceImpl <-- ProfileRetrievalService : UserPublicProfile
deactivate ProfileRetrievalService

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
DFSPublicKeyServiceImpl <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> DFSSystem : publicKeyStoreAuth

activate DFSSystem
' de.adorsys.datasafe.business.impl.profile.DFSSystem
DFSPublicKeyServiceImpl <-- DFSSystem : KeyStoreAuth
deactivate DFSSystem

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DFSPublicKeyServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
DFSPublicKeyServiceImpl -> KeyStoreService : getPublicKeys

activate KeyStoreService
' de.adorsys.datasafe.business.api.encryption.keystore.KeyStoreService
KeyStoreService -> KeyStoreServiceImpl : getPublicKeys

activate KeyStoreServiceImpl
' de.adorsys.datasafe.business.impl.keystore.service.KeyStoreServiceImpl
KeyStoreService <-- KeyStoreServiceImpl : List
deactivate KeyStoreServiceImpl

' de.adorsys.datasafe.business.api.encryption.keystore.KeyStoreService
DFSPublicKeyServiceImpl <-- KeyStoreService : List

' de.adorsys.datasafe.business.impl.credentials.DFSPublicKeyServiceImpl
PublicKeyService <-- DFSPublicKeyServiceImpl : PublicKeyIDWithPublicKey
deactivate DFSPublicKeyServiceImpl

' de.adorsys.datasafe.business.api.directory.profile.keys.PublicKeyService
WriteToPrivateImpl <-- PublicKeyService : PublicKeyIDWithPublicKey
deactivate PublicKeyService

' de.adorsys.datasafe.business.impl.privatestore.actions.WriteToPrivateImpl
WriteToPrivateImpl -> DocumentWriteService : write

activate DocumentWriteService
' de.adorsys.datasafe.business.api.storage.document.DocumentWriteService
DocumentWriteService -> CMSDocumentWriteService : write

activate CMSDocumentWriteService
' de.adorsys.datasafe.business.impl.document.cms.CMSDocumentWriteService
CMSDocumentWriteService -> DFSConnectionService : obtain

activate DFSConnectionService
' de.adorsys.datasafe.business.api.storage.dfs.DFSConnectionService
CMSDocumentWriteService <-- DFSConnectionService : DFSConnection
deactivate DFSConnectionService

' de.adorsys.datasafe.business.impl.document.cms.CMSDocumentWriteService
CMSDocumentWriteService -> CMSEncryptionService : encrypt

activate CMSEncryptionService
' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
CMSEncryptionService -> CMSEncryptionServiceImpl : encrypt

activate CMSEncryptionServiceImpl
' de.adorsys.datasafe.business.impl.cmsencryption.services.CMSEncryptionServiceImpl
CMSEncryptionService <-- CMSEncryptionServiceImpl : CMSEnvelopedData
deactivate CMSEncryptionServiceImpl

' de.adorsys.datasafe.business.api.encryption.cmsencryption.CMSEncryptionService
CMSDocumentWriteService <-- CMSEncryptionService : CMSEnvelopedData
deactivate CMSEncryptionService

' de.adorsys.datasafe.business.impl.document.cms.CMSDocumentWriteService
CMSDocumentWriteService -> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
CMSDocumentWriteService <-- DFSConnection :  
deactivate DFSConnection

' de.adorsys.datasafe.business.impl.document.cms.CMSDocumentWriteService
DocumentWriteService <-- CMSDocumentWriteService :  
deactivate CMSDocumentWriteService

' de.adorsys.datasafe.business.api.storage.document.DocumentWriteService
WriteToPrivateImpl <-- DocumentWriteService :  
deactivate DocumentWriteService

deactivate WriteToPrivateImpl

@enduml
